[build]
  publish = "public"
  command = "python3 scripts/build-images.py && python3 src/build.py"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
